name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello, world!"
      - name: print current date
        run: echo "$(date)"
      - name: print working directory
        run: echo "$(ls -l)"