name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SHOULD_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run eslint
      - name: Run tests
        run: npm run test
      - name: Build the application
        run: npm run build
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: 'http://localhost:5000'
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' && env.SHOULD_SKIP == 'false' }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.ref == 'refs/heads/main' && env.SHOULD_SKIP == 'false' }}
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
      - name: Discord Success Notification
        if: success()
        uses: rjstone/discord-webhook-notify@c2597273488aeda841dd1e891321952b51f7996f
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: A new version of Pokedex deployed
 
      - name: Discord Failure Notification
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: rjstone/discord-webhook-notify@c2597273488aeda841dd1e891321952b51f7996f
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          details: Build Failed
 